env: local
definitions:
  - ./config/definitions.php
databases:
  default: sqlite
  sqlite:
    driver: sqlite
    path: ../app.db
cors:
  origins: ['*']
  methods: ['GET', 'POST', 'PUT', 'DELETE']
  headers.allow: ["Authorization", "Content-Type", "X-Key"]
  headers.expose: []
  credentials: false
  cache: 0
jwt:
  key: example
  expires: 3600
data:
  ip: 127.0.0.1
  dns: 1.1.1.1
