env: local
databases:
  default: sqlite
  sqlite:
    driver: sqlite
    path: ../sharedlinks.db
cors:
  origins: ['*']
  methods: ['GET', 'POST', 'PUT', 'DELETE']
  headers.allow: ["Authorization", "Content-Type", "X-Key"]
  headers.expose: []
  credentials: false
  cache: 0
key_public: /home/erick/proyectos/dashvpn/sharedlinks/public.pem
